version: '3.9'
services:
  minio:
    container_name: minio-test
    image: minio/minio
    command: minio server --console-address ":9001" /mnt/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_CONFIG_ENV=/etc/minio/minio.env
    volumes:
      - ./minio.env:/etc/minio/minio.env
      - ./data:/mnt/data 
