version: '3'
services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf

  web_server1:
    image: nginx:latest
    container_name: web_server1
    volumes:
      - ./web-server1:/usr/share/nginx/html

  web_server2:
    image: nginx:latest
    container_name: web_server2
    volumes:
      - ./web-server2:/usr/share/nginx/html
  
  web_server3:
    image: nginx:latest
    container_name: web_server3
    volumes:
      - ./web-server3:/usr/share/nginx/html
  